# Generated by Django 4.2.9 on 2024-10-29 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_provider', '0002_alter_service_provider_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service_provider',
            name='service_provider_image',
            field=models.ImageField(blank=True, default='default_image.jpg', null=True, upload_to='service_providers/'),
        ),
    ]
