# Generated by Django 4.2.9 on 2024-11-04 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_provider', '0003_alter_service_provider_service_provider_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service_provider',
            name='short_intro',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
